### ISSUE TITLE
Error in BotController Class Related to DTO Functionality (Branch: amauri)

### ISSUE THREAD

**Issue by Marco2002M** [AASCSOSA/ReacconMind#1]
An error was found in the BotController class on the amauri branch, specifically concerning the Data Transfer Object (DTO). The DTO is not functioning as expected, which is affecting the behavior of the controller.  

Steps to Reproduce:

Switch to the amauri branch.
Attempt to use the BotController with the expected DTO input.
Observe the malfunction or unexpected behavior.

**Comment by Amauri-Kun** [comment]
The error that occurred due to the DTO was due to a bad import in the controller class, verify that the import was made by springframework:
`import org.springframework.web.bind.annotation.RequestBody;`

And not by swagger:
`import io.swagger.v3.oas.annotations.parameters.RequestBody;`
